### ISSUE TITLE
Add users to a list in one request

### ISSUE THREAD

**Issue by fernandopg** [gellu/sendy-api#6]
Hi @gellu !

I was thinking about to create an api request to add o bunch of users to a list in one request. For example in some cases I need to add like 15k users to a new list and execute 15k request is crazy...

The api request to add one user now is:

```
POST /subscribers/user/add
```

I was thinking to add that request:

```
POST /subscribers/users/add (Content-Type: application/json)
PARAMS:
   list: list id
   users: a json object ej: [{email: xxx, name: yyy}]
```

Or maybe this other:

```
POST /lists/subscribers/add (Content-Type: application/json)
PARAMS:
   list: list id
   users: a json object ej: [{email: xxx, name: yyy}]
```

Examples:

```
POST /subscribers/users/add (Content-Type: application/json)
{list:2, users: [...]}

POST /lists/subscribers/add (Content-Type: application/json)
{list:2, users: [...]}
```

Or maybe is better to keep the Content-Type as it is in the other api requests:

```
POST /subscribers/users/add (Content-Type: application/x-www-form-encoded)
list=2&users=[...]
```

What do you think?  Tell me if you would like to have that in your API and how do you think is better!

**Comment by gellu** [comment]
Good idea:)
I would rather use one route for that
`POST /subscribers/user/add`
If there is request body containing json list I would add multiple users, in other case (request body empty) to maintain backwards compatibility I would fallback to getting user data from POST.
Listid should be always passed with POST.

**Comment by fernandopg** [comment]
Ok, summarizing;

```
POST /subscribers/user/add (Content-Type: application/x-www-form-encoded)
PARAMS:
    list: list id
    email: user email (optional)
    name: name email (optional)
    users: [...] (optional)
```

If the users param exists I use it, if not I use the email and name params.

Examples:

```
Actual request:
POST /subscribers/user/add (Content-Type: application/x-www-form-encoded)
Body Request: list=1&email=xxx@yy.co&name=zzz

New request:
POST /subscribers/user/add (Content-Type: application/x-www-form-encoded)
Body Request: list=1&users=[{email:"xxx@yyy.co", name:"pepe"}, ...]
```

That's ok?
